Vagrant.configure(2) do |config|
  config.vm.define "lamp" do |web|
    web.vm.box = "ubuntu/trusty64" #vm.box = "apache"#
    web.vm.hostname = "lamp"
    web.vm.network :forwarded_port, guest: 8081, host: 8081
    web.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
    end
  end
end
